config/routes.rb
Rails.application.routes.draw do

  # The actions that are standard in Rails are:
  # new -> display form to create a record
  # create -> handle creating the record
  # edit -> display form to edit a record
  # update -> handle updating the record
  # index -> list a group of records
  # show -> display one record
  # destroy -> delete a record

  # users -> references users controller
  resources :users, only: [:new, :create]
  # the line above generates routes to all the standard 7 actions in Rails
  # unless you restrict it with `except` or `only`

  resources :notes

  get "/sign_in", to: "sessions#new"
  post "/sign_in", to: "sessions#create"
  delete "/sign_out", to: "sessions#destroy"

  # when we receive an HTTP `GET` request to a URL `/`
  # then handle it with `pages` controller
  # and use the `index` action (method)
  # get '/', to: 'pages#index'
  root to: 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates :title, presence: true

  # active record has many callbacks (hooks) that get executed at different times
  # during the lifecycle of the activerecord object
  before_save :convert_markdown_to_html

  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(new_list) # new_list is assumed to be a list separated by commas
    self.tags = new_list.split(',').map do |item|
      Tag.where(name: item.strip).first_or_create
    end
  end

  private

  def convert_markdown_to_html
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
    self.body_html = markdown.render(self.body_md)
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :notes, through: :taggings

  validates :name, presence: true, uniqueness: true
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :note
  belongs_to :tag
end

app/models/user.rb
# Rails convention is to use singular names for models
# that map to the pluralized version of the name as the table name
# User -> users table
# Category -> categories
# Wolf -> wolves
class User < ApplicationRecord
  # Rails will automatically `pick up` and set attributes based
  # on the columns in the table

  has_secure_password
  # the line above `has_secure_password` adds lots of things to our model:
  # 1- it adds two virtual attributes (ones that don't map to DB columns), which are 
  #    password & password_confirmation
  # 2- It validates that password must exist
  # 3- If you include `password_confirmation`, it ensures that it matches `password`
  # 4- It generates random salt, hashes the salt + password and stores the result in a DB field
  #    that is called `password_digest`

  # Validations
  validates(:first_name, { presence: true })
  validates :last_name, presence: true
  validates :email, presence: true,
                    uniqueness: true,
                    format: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

                   
  # the dependent: :destroy option says that if we delete a user
  # record, go ahead and delete all associated notes
  has_many :notes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def user_signed_in?
    session[:user_id].present?
  end
  helper_method :user_signed_in? 

  def current_user
    User.find(session[:user_id])
  end
  helper_method :current_user

  def authenticate_user!
    redirect_to root_path unless user_signed_in?
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user_note, only: [:show, :edit, :update, :destroy]

  def new
    @note = Note.new
  end

  def create
    @note = Note.new note_params
    @note.user = current_user
    if @note.save
      redirect_to notes_path, notice: 'Note created!'
    else
      render :new
    end
  end

  def index
    @notes = current_user.notes # this fetches all the notes for the current_user
  end

  def show
  end

  def edit
  end

  def update
    if @note.update(note_params)
      redirect_to note_path(@note), notice: 'Note updated'
    else
      render :edit
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_path, notice: 'Note deleted'
  end

  private

  def find_user_note
    @note = current_user.notes.find params[:id]
  end

  def note_params
    params.require(:note).permit(:title, :body_md, :tag_list)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  # we call methods in controllers `actions`
  def index
    # by default (convetion) this method will attempt to render
    # a file inside app/views/pages 
    # that has the same method name `index`
    # and by default it will use extension `.html.erb`
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Signed in'
    else
      redirect_to sign_in_path, alert: 'wrong credentials'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Signed out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # this is needed to display the form for the user to sign up
  def new
    # when we have an instance variable (starts with @)
    # the variable is accessible in the view file
    @user = User.new
  end

  # this is needed to handle the form submission to create the user
  def create
    user_params = params.require(:user).permit([:first_name, :last_name, :email, :password])
    @user = User.new(user_params)
    if @user.save # .save will return `true` if no validation errors are there
      session[:user_id] = @user.id # we sign the user in by storing their ID in the session
      redirect_to root_path
    else
      render :new # show the form again for the user to correct errors
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notely</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="container">

      <!-- <a href="/">Home</a> -->
      <%# the line below 👇 generates the line above 👆 %>
      <div class="row">
        <div class="col">
          <%= link_to("Home", root_path) %>
        </div>
        <div class="col text-right">
          <% if user_signed_in? %>
            Hello <%= current_user.first_name %> |
            <%= link_to "New Note", new_note_path %>
            |
            <%= link_to "Your Notes", notes_path %>
            |
            <%= link_to "Sign out", sign_out_path, method: :delete %>
          <% end %>
        </div>
      </div>
      <hr>
      
      <% if flash[:notice] %>
        <div class="alert alert-success" role="alert">
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger" role="alert">
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<% if @note.errors.any? %>
  <ul>
    <% @note.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @note do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body_md, 'Body Markdown' %>
    <%= f.text_area :body_md, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list, class: "form-control" %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/notes/edit.html.erb
<h1>Edit Note</h1>

<%= render 'form' %>

app/views/notes/index.html.erb
<h1>Your Notes</h1>

<% @notes.each do |note| %>
  <%= link_to note.title, note_path(note) %>
  <%= note.body_md.truncate(200) %>
  <hr>
<% end %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%# this will look for a file called `_form` within the same folder 
    all instance variables accessible here will be accessible in the 
    partial %>
<%= render 'form' %>

app/views/notes/show.html.erb
<div class="row">
  <div class="col">
    <h1><%= @note.title %></h1>
  </div>
  <div class="col">
    <% @note.tags.each do |tag| %>
      <code>#<%= tag.name %></code>
    <% end %>
  </div>
  <div class="col text-right">
    <%= link_to 'Edit', edit_note_path(@note), class: 'btn btn-info' %>
    <%= link_to 'Delete', note_path(@note), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
  </div>
</div>


<p><%= @note.body_html.html_safe %></p>

app/views/pages/index.html.erb
<h1>Welcome to Notely</h1>

<%= link_to "Sign Up", new_user_path, class: "btn btn-primary" %>
<%= link_to "Sign In", sign_in_path, class: "btn btn-info" %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%# if you want to create a record in the DB, always use `form_for` if 
    you are using it with ActiveRecord because it makes generating the form
    much easier %>
<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>